### ISSUE TITLE
type hint "object" in method signature does not seem to work with php 7.1

### ISSUE THREAD

**Issue by jmfeurprier** [andreiavrammsd/serializer#1]
In class Serializer\Parser\Parser , the following methods:

```
parseClass(\ReflectionClass $reflectionClass, object $object, array $data)
parseProperties(\ReflectionClass $reflectionClass, object $object, array $data)
```

have "object" as type hints, which cause the following error with PHP 7.1.12 (my current local version):

```
Argument 2 passed to Serializer\Parser\Parser::parseClass() must be an instance of Serializer\Parser\object, instance of Apixu\Response\CurrentWeather given, called in [...]/vendor/andreiavrammsd/serializer/src/Parser/Parser.php on line 46
```

I removed the "object" type hints locally and now it's working.

Would you consider removing these, or raising the php version requirement in composer.json to a more recent version of PHP (It may be working with 7.2, but I did not test it)?

Thanks !

**Comment by andreiavrammsd** [comment]
Thanks for letting me know! I will make it compatible with 7.1.
